version: '3.5'

services:
  db:
    image: postgres:10.6
    restart: always
    command: postgres -c log_statement=all -c logging_collector=on -c log_destination=stderr
    volumes:
      - db_data:/var/lib/postgres
    environment:
      POSTGRES_USER: devblock
      POSTGRES_PASSWORD: Abc12345_staging
      POSTGRES_DB: book_manager_staging
      POSTGRES_INITDB_WALDIR: /logs
    ports:
      - "5432:5432"

  api:
    depends_on:
      - db
    build: .
    restart: always
    environment:
      NODE_ENV: staging
      SERVER_PORT: 3000
      PSQL_HOST: db
      PSQL_PORT: 5432
      PSQL_USER: devblock
      PSQL_PASSWORD: Abc12345_staging
      PSQL_DATABASE: book_manager_staging
    ports:
      - "8080:3000"

volumes:
  db_data: