version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
      - image: circleci/postgres:10.6
        environment:
          POSTGRES_USER: devblock
          POSTGRES_DB: book_manager_test
          POSTGRES_PASSWORD: Abc12345_test

    working_directory: ~/book_manager

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: npm i

      - save_cache:
          paths:
            - ./dependencies
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: run tests
          command: make test.unit

      - store_artifacts:
          path: coverage
          destination: coverage
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      # - add_ssh_keys:
      #   fingerprints:
      #     - "a4:ad:5f:97:13:bc:52:f2:3c:7f:7d:df:37:a1:cd:df"
      - checkout
      - run:
          name: Add Dokku to known_hosts
          command: |
            ssh-keyscan -H 68.183.190.179 >> ~/.ssh/known_hosts
            ssh-keyscan -H bookmanager.ga >> ~/.ssh/known_hosts
      - run:
          name: Deploy to Dokku
          command: git push -f dokku@68.183.190.179:book-manager master

workflows:
  version: 2

  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master