CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS books(
  book_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title VARCHAR (200) NOT NULL,
  description VARCHAR (5000) NOT NULL,
  isbn CHAR(10) NOT NULL,
  author_name VARCHAR(100),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

